import { Audiowide, Montserrat } from 'next/font/google'

import type { Metadata } from 'next'
import '../globals.css'

const audiowide = Audiowide({
    weight: ['400'],
    variable: '--font-audiowide',
})

const montserrat = Montserrat({
    variable: '--font-montserrat',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'Fantasy Football - Authentication',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body className={`${audiowide.variable} ${montserrat.variable} antialiased`}>
                <main className="h-svh flex items-center justify-center">
                    <section className="flex p-2 border border-primary rounded-2xl min-h-[70vh] w-full max-w-5xl">
                        <div className="flex-1 p-10">{children}</div>
                        <div className="flex-1 rounded-xl bg-primary"></div>
                    </section>
                </main>
            </body>
        </html>
    )
}
